name: Deploy

env:

  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}

  GCLOUD_ZONE: ${{ secrets.GCLOUD_ZONE  }}
  GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
  GCLOUD_SA_KEY: ${{ secrets.GCLOUD_SA_KEY }}

  K8S_NS: ${{ secrets.K8S_NS }}

on:
  repository_dispatch:
    types: [ deploy-event ]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ env.GCLOUD_SA_KEY }}
          project_id: ${{ env.GCLOUD_PROJECT }}
          export_default_credentials: true

      - run: |-
          gcloud config set project $GCLOUD_PROJECT
          gcloud --quiet auth configure-docker
          gcloud container clusters get-credentials $GKE_CLUSTER_NAME --zone "$GCLOUD_ZONE" --project $GCLOUD_PROJECT

      - name: Deploy
        run: |
          cd $GITHUB_WORKSPACE/.github/workflows/
          ./deploy.sh
